services:
  bot:
    build: .
    command: python bot.py
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  engine:
    build: .
    command: python backend/index.py
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
